### ISSUE TITLE
Can't load the python script paths?

### ISSUE THREAD

**Issue by mani-nesan** [adchilds/JythonScript#1]
When I  used //String filePath = ClassLoader.getSystemResource("test2.py").getPath();// and created a python file named test2.py in the same directory, program shows a nullpointer exception in this line! what to do?

**Comment by adchilds** [comment]
It seems like the file you're trying to find (test2.py) cannot be found by the system ClassLoader.

I'd suggest passing a direct file reference (if you can) to JythonScript, as such:

    String filePath = "C:\Users\.....\test2.py";
    File file = new File(filePath);
    JythonScript.execute(file);

You could also just pass the `filePath` to `#execute(...)` and `#evaluate(...)` directly.

Does that work for you? If so, this may be an opportunity for me to clean up the documentation to showcase an approach that's more bug-proof.

Alternatively, try playing around with the path to your test script until it's found. This may require you to prepend test2.py with some directories as you can see in JythonScript's tests. I prepend `/scripts/jython/` to the file name: https://github.com/adchilds/JythonScript/blob/develop/src/test/java/com/github/adchilds/jython/JythonScriptTest.java#L54

**Comment by adchilds** [comment]
The scope of this issue falls outside of JythonScript, though we could clean up our documentation and examples to show other ways of finding/using Python code with JythonScript. I've tagged this and thrown it into my queue to update the documentation.

Closing this ticket. Feel free to open another ticket if you're not satisfied with this result.
